version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASSWORD=yourpassword
